pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "TechHurtsWidgets"
include ':app'
include ':calculator'
include ':goeseast'
include ':himawari8'
include ':hisense_remote'
include ':timer'
include ':app-weather'
include ':app-calc'
include ':app-goes'
include ':app-himawari'
include ':app-remote'
include ':app-timer'
include ':widgets'
