// app/build.gradle (Module level)
plugins {
    id 'com.android.application'
}

def appVersionCode = project.hasProperty('versionCode') ? versionCode.toInteger() : 1

android {
    namespace 'com.techhurts.weatherwidget'
    compileSdk 34

    defaultConfig {
        applicationId "com.techhurts.weatherwidget"
        minSdk 21
        targetSdk 34
        versionCode appVersionCode
        versionName "1.0.0.${appVersionCode}"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    signingConfigs {
        debug {
            storeFile file("../debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding false
        dataBinding false
        resValues false
        buildConfig false
    }
}

dependencies {
}
