plugins {
    id 'com.android.application'
}

android {
    namespace 'com.techhurts.hisense_remote'
    compileSdk 34

    defaultConfig {
        applicationId "com.techhurts.hisense_remote"
        minSdk 21
        targetSdk 34
        versionCode((project.findProperty('appVersionCode') ?: '1').toInteger())
        versionName project.findProperty('appVersionName') ?: '0.0000.000-dev'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding false
        dataBinding false
        resValues false
        buildConfig false
    }
}

dependencies {
    implementation 'org.bouncycastle:bcprov-jdk15on:1.70'
    implementation 'com.google.protobuf:protobuf-java:3.11.4'
}
